CREATE TABLE "customer" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "external_id" varchar UNIQUE,
  "name" varchar,
  "email" varchar UNIQUE,
  "address" text,
  "latitude" float(53),
  "longitude" float(53),
  "created_at" timestamptz NOT NULL DEFAULT 'now()',
  "updated_at" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE TABLE "region" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE,
  "active" boolean,
  "created_at" timestamptz NOT NULL DEFAULT 'now()',
  "updated_at" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE TABLE "payment_method" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE,
  "active" boolean,
  "created_at" timestamptz NOT NULL DEFAULT 'now()',
  "updated_at" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE TABLE "category" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE,
  "active" boolean,
  "created_at" timestamptz NOT NULL DEFAULT 'now()',
  "updated_at" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE TABLE "product" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "external_id" varchar UNIQUE,
  "name" varchar,
  "description" text,
  "price" float,
  "category_id" integer,
  "active" boolean,
  "created_at" timestamptz NOT NULL DEFAULT 'now()',
  "updated_at" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE TABLE "order" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "external_id" varchar UNIQUE,
  "product_id" integer,
  "customer_id" integer,
  "payment_method_id" integer,
  "region_id" integer,
  "discount" float,
  "shipping_cost" float,
  "quantity" integer,
  "date_of_sales" timestamptz NOT NULL,
  "total_cost" float,
  "actual_cost" float,
  "created_at" timestamptz NOT NULL DEFAULT 'now()',
  "updated_at" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE INDEX "idx_customer_external_id" ON "customer" ("external_id");

CREATE INDEX "idx_region_name" ON "region" ("name");

CREATE INDEX "idx_payment_method_name" ON "payment_method" ("name");

CREATE INDEX "idx_category_name" ON "category" ("name");

CREATE INDEX "idx_product_category" ON "product" ("category_id");

CREATE INDEX "idx_product_external_id" ON "product" ("external_id");

CREATE INDEX "idx_order_external_id" ON "order" ("external_id");

CREATE INDEX "idx_date_of_sales" ON "order" ("date_of_sales");

CREATE INDEX "idx_order_customer_date" ON "order" ("customer_id", "date_of_sales");

CREATE INDEX "idx_order_product_date" ON "order" ("product_id", "date_of_sales");

CREATE INDEX "idx_order_region_date" ON "order" ("region_id", "date_of_sales");

CREATE INDEX "idx_order_product_quantity_date" ON "order" ("product_id", "date_of_sales", "quantity");

CREATE INDEX "idx_prder_product_region_date" ON "order" ("product_id", "region_id", "date_of_sales");

COMMENT ON COLUMN "customer"."latitude" IS 'double precision';

COMMENT ON COLUMN "customer"."longitude" IS 'double precision';

ALTER TABLE "product" ADD FOREIGN KEY ("category_id") REFERENCES "category" ("id");

ALTER TABLE "order" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id");

ALTER TABLE "order" ADD FOREIGN KEY ("customer_id") REFERENCES "customer" ("id");

ALTER TABLE "order" ADD FOREIGN KEY ("payment_method_id") REFERENCES "payment_method" ("id");

ALTER TABLE "order" ADD FOREIGN KEY ("region_id") REFERENCES "region" ("id");
